import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Note: `eslint-config-next/core-web-vitals` bundles `eslint-plugin-jsx-a11y` (verified with @16.2.6).
// Do NOT register jsx-a11y separately (causes ConfigError: "Cannot redefine plugin jsx-a11y").
// ⚠️ On Next.js upgrade: Verify jsx-a11y is still bundled via `npx eslint --debug | grep jsx-a11y`
// See: Story 1.13 (CI configuration for version verification).
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Serwist compiled service worker output — generated file, not source
    "public/sw.js",
    // Coverage report output — generated by vitest, not source
    "coverage/**",
  ]),
  // Restrict service-role client imports to whitelisted server-only paths.
  // The service-role client bypasses RLS — importing it in browser/page code
  // would expose the service key and remove all multi-tenant isolation.
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/lib/supabase/service-role", "@/lib/supabase/service-role"],
              message:
                "❌ Service-role client is restricted. Use @/lib/supabase/client (browser) or @/lib/supabase/server (server) instead. Allowed only in supabase/functions/ and src/lib/actions/.",
            },
          ],
        },
      ],
    },
  },
  // Allow service-role imports in whitelisted server-only locations.
  {
    files: [
      "supabase/functions/**",
      "src/lib/supabase/service-role.ts",
      "src/lib/actions/**",
      "scripts/**",
    ],
    rules: {
      "no-restricted-imports": "off",
      // scripts/ uses CommonJS require() — Node.js scripts run outside ESM bundler
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Test files: relax rules that don't apply cleanly to mocking patterns.
  {
    files: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
      "__tests__/**/*",
    ],
    rules: {
      // Test mocks commonly cast to `any` for partial implementations
      "@typescript-eslint/no-explicit-any": "off",
      // Test files may import service-role client to set up test data
      "no-restricted-imports": "off",
    },
  },
]);

export default eslintConfig;
