/**
 * Integration tests for MFA flows (Story 1.7)
 *
 * These tests require a local Supabase instance running:
 *   supabase start
 *
 * To run:
 *   SUPABASE_INTEGRATION=true npm run test -- --run __tests__/mfa.integration.test.ts
 *
 * For TOTP code generation in itIntegration tests, install:
 *   npm install --save-dev otplib
 * Then use: import { authenticator } from "otplib"; const code = authenticator.generate(secret);
 *
 * All tests are skipped unless SUPABASE_INTEGRATION=true.
 */
import { describe, it, expect, beforeAll } from "vitest";

const INTEGRATION = process.env.SUPABASE_INTEGRATION === "true";
const itIntegration = INTEGRATION ? it : it.skip;

// ---------------------------------------------------------------------------
// Integration test fixtures (must match supabase/seed.sql from Story 1.6)
// ---------------------------------------------------------------------------

const COACH_EMAIL = "coach@SPARTA.test";
const COACH_PASSWORD = "testpassword123!";
const PLAYER_EMAIL = "player@SPARTA.test";
const PLAYER_PASSWORD = "testpassword123!";

// ---------------------------------------------------------------------------
// Client setup
// ---------------------------------------------------------------------------

type SupabaseClient = Awaited<
  ReturnType<typeof import("@/lib/supabase/client").createClient>
>;
let supabase: SupabaseClient;

beforeAll(async () => {
  if (!INTEGRATION) return;
  const { createClient } = await import("@/lib/supabase/client");
  supabase = createClient();
});

// ---------------------------------------------------------------------------
// AC #1 + AC #2 — Enrollment end-to-end
// ---------------------------------------------------------------------------

describe("AC #1 + #2 — TOTP enrollment end-to-end (local Supabase)", () => {
  itIntegration("enrolls TOTP and returns qr_code + secret", async () => {
    await supabase.auth.signInWithPassword({ email: COACH_EMAIL, password: COACH_PASSWORD });

    const { data, error } = await supabase.auth.mfa.enroll({ factorType: "totp" });
    expect(error).toBeNull();
    expect(data?.totp.qr_code).toBeTruthy();
    expect(data?.totp.secret).toBeTruthy();
    expect(data?.id).toBeTruthy();

    // Cleanup: remove unverified factor
    if (data?.id) {
      await supabase.auth.mfa.unenroll({ factorId: data.id });
    }
  });

  itIntegration("challengeAndVerify activates MFA with valid code", async () => {
    // Pre-condition: install otplib (npm install --save-dev otplib) to generate real codes.
    // This test documents the expected API contract; run it with a valid TOTP code
    // generated by an authenticator app after scanning the QR code from enrollment.
    await supabase.auth.signInWithPassword({ email: COACH_EMAIL, password: COACH_PASSWORD });

    const { data: enrollData, error: enrollError } = await supabase.auth.mfa.enroll({
      factorType: "totp",
    });
    expect(enrollError).toBeNull();
    expect(enrollData?.id).toBeTruthy();

    // In a live test with otplib:
    // const { authenticator } = require("otplib");
    // const code = authenticator.generate(enrollData.totp.secret);
    // const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId: enrollData.id, code });
    // expect(error).toBeNull();

    // Cleanup
    if (enrollData?.id) {
      await supabase.auth.mfa.unenroll({ factorId: enrollData.id });
    }
  });
});

// ---------------------------------------------------------------------------
// AC #3 — Player accounts
// ---------------------------------------------------------------------------

describe("AC #3 — Player role isolation", () => {
  itIntegration("player can sign in without MFA restriction", async () => {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: PLAYER_EMAIL,
      password: PLAYER_PASSWORD,
    });
    expect(error).toBeNull();
    expect(data.session).toBeTruthy();
  });

  itIntegration("player AAL level is aal1 (no MFA enrolled)", async () => {
    await supabase.auth.signInWithPassword({ email: PLAYER_EMAIL, password: PLAYER_PASSWORD });

    const { data: aalData } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
    // Player has no MFA enrolled, so both levels should be aal1
    expect(aalData?.currentLevel).toBe("aal1");
  });
});

// ---------------------------------------------------------------------------
// AC #4 — Login AAL detection
// ---------------------------------------------------------------------------

describe("AC #4 — Login MFA challenge detection (local Supabase)", () => {
  itIntegration("password login returns session at aal1 initially", async () => {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: COACH_EMAIL,
      password: COACH_PASSWORD,
    });
    expect(error).toBeNull();
    expect(data.session).toBeTruthy();

    const { data: aalData } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
    // With no MFA enrolled: currentLevel = aal1, nextLevel = aal1
    // With MFA enrolled: currentLevel = aal1, nextLevel = aal2
    expect(["aal1", "aal2"]).toContain(aalData?.currentLevel);
  });

  itIntegration("listFactors returns empty totp array when no MFA enrolled", async () => {
    await supabase.auth.signInWithPassword({ email: COACH_EMAIL, password: COACH_PASSWORD });

    const { data, error } = await supabase.auth.mfa.listFactors();
    expect(error).toBeNull();
    // With no enrolled MFA, totp array is empty
    const verifiedFactors = data?.totp?.filter((f) => f.status === "verified") ?? [];
    expect(Array.isArray(verifiedFactors)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// AC #5 — Disable MFA
// ---------------------------------------------------------------------------

describe("AC #5 — Disable MFA with password confirmation (local Supabase)", () => {
  itIntegration("unenroll removes a verified factor", async () => {
    await supabase.auth.signInWithPassword({ email: COACH_EMAIL, password: COACH_PASSWORD });

    // Enroll a factor (unverified — still testable for unenroll)
    const { data: enrollData, error: enrollError } = await supabase.auth.mfa.enroll({
      factorType: "totp",
    });
    expect(enrollError).toBeNull();
    expect(enrollData?.id).toBeTruthy();

    // Unenroll the factor
    const { error: unenrollError } = await supabase.auth.mfa.unenroll({
      factorId: enrollData!.id,
    });
    expect(unenrollError).toBeNull();

    // Verify it's gone
    const { data: factors } = await supabase.auth.mfa.listFactors();
    const remaining = factors?.totp?.find((f) => f.id === enrollData!.id);
    expect(remaining).toBeUndefined();
  });

  itIntegration("password re-auth succeeds with correct password", async () => {
    const { error } = await supabase.auth.signInWithPassword({
      email: COACH_EMAIL,
      password: COACH_PASSWORD,
    });
    expect(error).toBeNull();
  });

  itIntegration("password re-auth fails with wrong password", async () => {
    const { error } = await supabase.auth.signInWithPassword({
      email: COACH_EMAIL,
      password: "wrong-password",
    });
    expect(error).not.toBeNull();
  });
});
